Repository PiqProject/piqProject, pull requests merged in 2025-09, with the labels that each got.

#2 feat(common): 공통 예외 처리 시스템 구축
  build.gradle
  src/main/java/piq/piqproject/common/error/dto/ErrorDetailsDto.java
  src/main/java/piq/piqproject/common/error/dto/ErrorResponseDto.java
  src/main/java/piq/piqproject/common/error/dto/ValidErrorResponseDto.java
  src/main/java/piq/piqproject/common/error/exception/ConflictException.java
  src/main/java/piq/piqproject/common/error/exception/CustomException.java
  src/main/java/piq/piqproject/common/error/exception/ErrorCode.java
  src/main/java/piq/piqproject/common/error/exception/ForbiddenException.java
  src/main/java/piq/piqproject/common/error/exception/InternalServerException.java
  src/main/java/piq/piqproject/common/error/exception/InvalidRequestException.java
  src/main/java/piq/piqproject/common/error/exception/NotFoundException.java
  src/main/java/piq/piqproject/common/error/exception/UnauthorizedException.java
  src/main/java/piq/piqproject/common/error/handle/GlobalExceptionHandler.java
  src/main/java/piq/piqproject/config/jwt/JwtFilter.java
  src/main/java/piq/piqproject/config/jwt/JwtTokenProvider.java
  src/main/java/piq/piqproject/config/jwt/SecurityConfig.java
  src/main/java/piq/piqproject/domain/users/service/UserService.java
  src/main/resources/application.properties
Labels: feat, refactor

#5 refactor(security): Refactoring Filter, UserService.reissueAccessToken()
  src/main/java/piq/piqproject/common/error/exception/ErrorCode.java
  src/main/java/piq/piqproject/config/jwt/JwtExceptionFilter.java
  src/main/java/piq/piqproject/config/jwt/JwtFilter.java
  src/main/java/piq/piqproject/config/jwt/JwtTokenProvider.java
  src/main/java/piq/piqproject/config/jwt/SecurityConfig.java
  src/main/java/piq/piqproject/domain/users/service/UserService.java
Labels: bug, refactor, fix

#6 feat(review): Implements review CRUD
  src/main/java/piq/piqproject/PiqProjectApplication.java
  src/main/java/piq/piqproject/common/error/exception/ErrorCode.java
  src/main/java/piq/piqproject/config/jwt/SecurityConfig.java
  src/main/java/piq/piqproject/domain/reviews/.gitkeep
  src/main/java/piq/piqproject/domain/reviews/controller/.gitkeep
  src/main/java/piq/piqproject/domain/reviews/controller/ReviewController.java
  src/main/java/piq/piqproject/domain/reviews/dao/.gitkeep
  src/main/java/piq/piqproject/domain/reviews/dao/ReviewDao.java
  src/main/java/piq/piqproject/domain/reviews/dto/.gitkeep
  src/main/java/piq/piqproject/domain/reviews/dto/ReviewRequestDto.java
  src/main/java/piq/piqproject/domain/reviews/dto/ReviewResponseDto.java
  src/main/java/piq/piqproject/domain/reviews/entity/.gitkeep
  src/main/java/piq/piqproject/domain/reviews/entity/ReviewEntity.java
  src/main/java/piq/piqproject/domain/reviews/repository/.gitkeep
  src/main/java/piq/piqproject/domain/reviews/repository/ReviewRepository.java
  src/main/java/piq/piqproject/domain/reviews/service/ReviewService.java
  src/main/java/piq/piqproject/domain/users/service/UserService.java
Labels: feat

#7 user CRUD 구현
  src/main/java/piq/piqproject/common/error/dto/ErrorDetailsDto.java
  src/main/java/piq/piqproject/common/error/handle/GlobalExceptionHandler.java
  src/main/java/piq/piqproject/common/list/ListResponseDto.java
  src/main/java/piq/piqproject/common/list/Listable.java
  src/main/java/piq/piqproject/config/jwt/JwtFilter.java
  src/main/java/piq/piqproject/config/jwt/JwtTokenProvider.java
  src/main/java/piq/piqproject/config/springsecurity/CustomAccessDeniedHandler.java
  src/main/java/piq/piqproject/config/springsecurity/CustomAuthenticationEntryPoint.java
  src/main/java/piq/piqproject/config/springsecurity/SecurityConfig.java
  src/main/java/piq/piqproject/config/springsecurity/UserDetailsServiceImpl.java
  src/main/java/piq/piqproject/domain/reviews/entity/ReviewEntity.java
  src/main/java/piq/piqproject/domain/users/controller/UserController.java
  src/main/java/piq/piqproject/domain/users/dao/UserDao.java
  src/main/java/piq/piqproject/domain/users/dto/LoginRequestDto.java
  src/main/java/piq/piqproject/domain/users/dto/MyProfileResponseDto.java
  src/main/java/piq/piqproject/domain/users/dto/SignUpRequestDto.java
  src/main/java/piq/piqproject/domain/users/dto/SignUpResponseDto.java
  src/main/java/piq/piqproject/domain/users/dto/TokensResponseDto.java
  src/main/java/piq/piqproject/domain/users/dto/UserProfileResponseDto.java
  src/main/java/piq/piqproject/domain/users/dto/UserSimpleProfileResponseDto.java
  src/main/java/piq/piqproject/domain/users/entity/RefreshTokenEntity.java
  src/main/java/piq/piqproject/domain/users/entity/UserEntity.java
  src/main/java/piq/piqproject/domain/users/repository/UserRepository.java
  src/main/java/piq/piqproject/domain/users/service/UserService.java
Labels: feat

#9 feat(post): 게시글 (공지사항, 이벤트) CRUD 구현
  src/main/java/piq/piqproject/common/error/exception/ErrorCode.java
  src/main/java/piq/piqproject/common/error/handle/GlobalExceptionHandler.java
  src/main/java/piq/piqproject/common/util/RoleUtils.java
  src/main/java/piq/piqproject/common/util/TimeUtils.java
  src/main/java/piq/piqproject/config/springsecurity/SecurityConfig.java
  src/main/java/piq/piqproject/domain/events/controller/.gitkeep
  src/main/java/piq/piqproject/domain/events/dao/.gitkeep
  src/main/java/piq/piqproject/domain/events/dto/.gitkeep
  src/main/java/piq/piqproject/domain/events/entity/.gitkeep
  src/main/java/piq/piqproject/domain/events/repository/.gitkeep
  src/main/java/piq/piqproject/domain/posts/controller/PostController.java
  src/main/java/piq/piqproject/domain/posts/dto/request/AnnouncementRequestDto.java
  src/main/java/piq/piqproject/domain/posts/dto/request/EventRequestDto.java
  src/main/java/piq/piqproject/domain/posts/dto/response/PostResponseDto.java
  src/main/java/piq/piqproject/domain/posts/entity/PostEntity.java
  src/main/java/piq/piqproject/domain/posts/entity/PostType.java
  src/main/java/piq/piqproject/domain/posts/repository/.gitkeep
  src/main/java/piq/piqproject/domain/posts/repository/PostRepository.java
  src/main/java/piq/piqproject/domain/posts/service/PostService.java
  src/main/java/piq/piqproject/domain/reviews/controller/ReviewController.java
  src/main/java/piq/piqproject/domain/reviews/dto/ReviewResponseDto.java
  src/main/java/piq/piqproject/domain/reviews/service/ReviewService.java
  src/main/java/piq/piqproject/domain/users/entity/UserEntity.java
Labels: feat, refactor

#10 Refactoring (review,posts,images)
  build.gradle
  src/main/java/piq/piqproject/common/error/exception/ConflictException.java
  src/main/java/piq/piqproject/common/error/exception/CustomException.java
  src/main/java/piq/piqproject/common/error/exception/ErrorCode.java
  src/main/java/piq/piqproject/common/error/exception/ForbiddenException.java
  src/main/java/piq/piqproject/common/error/exception/InternalServerException.java
  src/main/java/piq/piqproject/common/error/exception/InvalidRequestException.java
  src/main/java/piq/piqproject/common/error/exception/NotFoundException.java
  src/main/java/piq/piqproject/common/error/exception/UnauthorizedException.java
  src/main/java/piq/piqproject/common/error/handle/GlobalExceptionHandler.java
  src/main/java/piq/piqproject/common/file/FileUploader.java
  src/main/java/piq/piqproject/common/file/FileUtil.java
  src/main/java/piq/piqproject/config/springsecurity/SecurityConfig.java
  src/main/java/piq/piqproject/config/webconfig/WebConfig.java
  src/main/java/piq/piqproject/domain/matches/dao/.gitkeep
  src/main/java/piq/piqproject/domain/payments/dao/.gitkeep
  src/main/java/piq/piqproject/domain/posts/controller/PostController.java
  src/main/java/piq/piqproject/domain/posts/dto/request/AnnouncementRequestDto.java
  src/main/java/piq/piqproject/domain/posts/dto/request/EventRequestDto.java
  src/main/java/piq/piqproject/domain/posts/dto/response/PostResponseDto.java
  src/main/java/piq/piqproject/domain/reviews/controller/ReviewController.java
  src/main/java/piq/piqproject/domain/reviews/dao/ReviewDao.java
  src/main/java/piq/piqproject/domain/reviews/dto/ReviewRequestDto.java
  src/main/java/piq/piqproject/domain/reviews/dto/ReviewResponseDto.java
  src/main/java/piq/piqproject/domain/reviews/repository/ReviewRepository.java
  src/main/java/piq/piqproject/domain/reviews/service/ReviewService.java
  src/main/java/piq/piqproject/domain/shop/dao/.gitkeep
  src/main/java/piq/piqproject/domain/userImages/.gitkeep
  src/main/java/piq/piqproject/domain/userImages/controller/.gitkeep
  src/main/java/piq/piqproject/domain/userImages/controller/UserImageController.java
  src/main/java/piq/piqproject/domain/userImages/dao/.gitkeep
  src/main/java/piq/piqproject/domain/userImages/dto/.gitkeep
  src/main/java/piq/piqproject/domain/userImages/dto/UserImageResponseDto.java
  src/main/java/piq/piqproject/domain/userImages/entity/.gitkeep
  src/main/java/piq/piqproject/domain/userImages/entity/UserImageEntity.java
  src/main/java/piq/piqproject/domain/userImages/repository/.gitkeep
  src/main/java/piq/piqproject/domain/userImages/repository/UserImageRepository.java
  src/main/java/piq/piqproject/domain/userImages/service/.gitkeep
  src/main/java/piq/piqproject/domain/userImages/service/UserImageService.java
  src/main/java/piq/piqproject/domain/users/controller/AuthController.java
  src/main/java/piq/piqproject/domain/users/controller/UserController.java
  src/main/java/piq/piqproject/domain/users/dao/UserDao.java
  src/main/java/piq/piqproject/domain/users/dto/request/LoginRequestDto.java
  src/main/java/piq/piqproject/domain/users/dto/request/SignUpRequestDto.java
  src/main/java/piq/piqproject/domain/users/dto/response/AccessTokenResponseDto.java
  src/main/java/piq/piqproject/domain/users/dto/response/MyProfileResponseDto.java
  src/main/java/piq/piqproject/domain/users/dto/response/SignUpResponseDto.java
  src/main/java/piq/piqproject/domain/users/dto/response/TokensResponseDto.java
  src/main/java/piq/piqproject/domain/users/dto/response/UserProfileResponseDto.java
  src/main/java/piq/piqproject/domain/users/dto/response/UserSimpleProfileResponseDto.java
  src/main/java/piq/piqproject/domain/users/entity/UserEntity.java
  src/main/java/piq/piqproject/domain/users/repository/UserRepository.java
  src/main/java/piq/piqproject/domain/users/service/AuthService.java
  src/main/java/piq/piqproject/domain/users/service/UserService.java
  src/main/java/piq/piqproject/infra/local/LocalUploader.java
  src/main/java/piq/piqproject/infra/s3/S3Uploader.java
  src/main/resources/application.properties
Labels: feat, refactor

#11 refactor(userRoles): userRoles추가하는 로직 변경
  build.gradle
  src/main/java/piq/piqproject/config/jwt/JwtTokenProvider.java
  src/main/java/piq/piqproject/config/springsecurity/UserDetailsServiceImpl.java
  src/main/java/piq/piqproject/domain/users/controller/AuthController.java
  src/main/java/piq/piqproject/domain/users/controller/UserController.java
  src/main/java/piq/piqproject/domain/users/dto/request/SignUpRequestDto.java
  src/main/java/piq/piqproject/domain/users/dto/response/MyProfileResponseDto.java
  src/main/java/piq/piqproject/domain/users/dto/response/UserProfileResponseDto.java
  src/main/java/piq/piqproject/domain/users/dto/response/UserSimpleProfileResponseDto.java
  src/main/java/piq/piqproject/domain/users/entity/UserEntity.java
  src/main/java/piq/piqproject/domain/users/entity/UserRoleEntity.java
  src/main/java/piq/piqproject/domain/users/enums/Gender.java
  src/main/java/piq/piqproject/domain/users/enums/Role.java
  src/main/java/piq/piqproject/domain/users/repository/UserRepository.java
  src/main/java/piq/piqproject/domain/users/service/AdminInitializer.java
  src/main/java/piq/piqproject/domain/users/service/AuthService.java
  src/main/java/piq/piqproject/domain/users/service/UserService.java
  src/main/resources/application.properties
Labels: refactor

#14 feat(matches): 매칭 CRUD 구현
  src/main/java/piq/piqproject/common/error/exception/ErrorCode.java
  src/main/java/piq/piqproject/common/error/handle/GlobalExceptionHandler.java
  src/main/java/piq/piqproject/config/jwt/JwtExceptionFilter.java
  src/main/java/piq/piqproject/config/jwt/JwtFilter.java
  src/main/java/piq/piqproject/config/webconfig/WebConfig.java
  src/main/java/piq/piqproject/domain/matches/.gitkeep
  src/main/java/piq/piqproject/domain/matches/controller/.gitkeep
  src/main/java/piq/piqproject/domain/matches/controller/MatchingController.java
  src/main/java/piq/piqproject/domain/matches/dto/.gitkeep
  src/main/java/piq/piqproject/domain/matches/dto/request/MatchingRequestDto.java
  src/main/java/piq/piqproject/domain/matches/dto/request/UpdateMatchingRequestDto.java
  src/main/java/piq/piqproject/domain/matches/dto/response/MatchingResponseDto.java
  src/main/java/piq/piqproject/domain/matches/dto/response/PartnerProfileDto.java
  src/main/java/piq/piqproject/domain/matches/entity/.gitkeep
  src/main/java/piq/piqproject/domain/matches/entity/MatchingEntity.java
  src/main/java/piq/piqproject/domain/matches/enums/MatchingStatus.java
  src/main/java/piq/piqproject/domain/matches/repository/.gitkeep
  src/main/java/piq/piqproject/domain/matches/repository/MatchingRepository.java
  src/main/java/piq/piqproject/domain/matches/service/.gitkeep
  src/main/java/piq/piqproject/domain/matches/service/MatchingService.java
  src/main/java/piq/piqproject/domain/users/controller/AuthController.java
  src/main/java/piq/piqproject/domain/users/controller/UserController.java
  src/main/java/piq/piqproject/domain/users/entity/UserEntity.java
  src/main/java/piq/piqproject/domain/users/service/UserService.java
  src/main/java/piq/piqproject/infra/s3/S3Uploader.java
Labels: feat

#15 Feat/matches 매칭하기 구현
  src/main/java/piq/piqproject/common/error/exception/ErrorCode.java
  src/main/java/piq/piqproject/domain/userImages/service/UserImageService.java
Labels: feat
